	["ACE-SFP-SL-TL",[["sfp_ak5c_m203","","","optic_Hamr",["sfp_30Rnd_556x45_Stanag_plastic",30],["1Rnd_HE_Grenade_shell",1],""],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_modern",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",3],["ACE_bloodIV_500",1],["ACE_bloodIV_250",1],["ACE_microDAGR",1],["ACE_morphine",4],["ACE_personalAidKit",1],["ACE_plasmaIV_500",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_elasticBandage",1],["ACE_Fortify",1],["ACE_RangeCard",1],["sfp_30Rnd_556x45_Stanag_irtracer",1,30],["sfp_17Rnd_9x19_Mag",1,17]]],["sfp_kroppsskydd12_tl",[["muzzle_snds_M",1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",6,30],["1Rnd_HE_Grenade_shell",4,1],["sfp_17Rnd_9x19_Mag",2,17],["SmokeShell",2,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1],["ACE_Chemlight_IR",1,1]]],["sfp_backpack_stridssack08",[["ACE_fieldDressing",2],["ACE_packingBandage",1],["ACE_quikclot",2],["ACE_bloodIV",1],["ACE_plasmaIV",1],["ACE_personalAidKit",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_splint",1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",2,30],["1Rnd_HE_Grenade_shell",8,1],["1Rnd_Smoke_Grenade_shell",2,1],["ACE_40mm_Flare_white",1,1],["ACE_40mm_Flare_green",1,1],["ACE_40mm_Flare_ir",1,1],["1Rnd_SmokeGreen_Grenade_shell",1,1]]],"sfp_m90w_helmet_peltor_nvg","G_Tactical_Black",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-JTac",[["sfp_ak5c_alt","","acc_pointer_IR","sfp_optic_3x_aimpoint",["sfp_30Rnd_556x45_Stanag_plastic",30],[],""],[],["sfp_p88","","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_modern",[["FirstAidKit",1],["NVGoggles",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_plastic",2,30]]],["sfp_kroppsskydd12_holster",[["sfp_30Rnd_556x45_Stanag_plastic",1,30],["sfp_30Rnd_556x45_Stanag",4,30],["SmokeShellGreen",2,1],["SmokeShell",2,1],["sfp_handgrenade_shgr56",2,1]]],[],"sfp_m90w_helmet_headset_nvg","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SAF-Marksman",[["sfp_ak5b","muzzle_snds_M","","optic_Hamr",["sfp_30Rnd_556x45_Stanag_plastic",30],[],""],[],["sfp_p88","","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_modern",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_bloodIV_500",1],["ACE_bloodIV_250",1],["ACE_microDAGR",1],["ACE_morphine",4],["ACE_personalAidKit",1],["ACE_tourniquet",2],["ACE_Fortify",1],["ACE_RangeCard",1],["O_NVGoggles_grn_F",1],["sfp_17Rnd_9x19_Mag",1,17]]],["sfp_kroppsskydd12_holster",[["SmokeShellGreen",1,1],["SmokeShell",3,1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_handgrenade_shgr2000",2,1],["sfp_handgrenade_shgr07",2,1],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",6,30]]],[],"sfp_m90w_cap","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-Medic",[["sfp_ak5c","","acc_pointer_IR","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_plastic",30],[],""],[],[],["sfp_m90w_uniform_modern",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_tourniquet",2],["ACE_splint",2],["ACE_salineIV_500",1],["ACE_plasmaIV_250",1],["ACE_Fortify",1],["sfp_30Rnd_556x45_Stanag_irtracer",1,30],["sfp_30Rnd_556x45_Stanag_tracer_plastic",1,30]]],["sfp_kroppsskydd12_medic",[["ACE_bloodIV_500",2],["ACE_salineIV_250",1],["ACE_plasmaIV_250",2],["ACE_morphine",2],["ACE_epinephrine",4],["ACE_adenosine",2],["ACE_fieldDressing",4],["ACE_elasticBandage",2],["ACE_packingBandage",4],["ACE_quikclot",4],["sfp_30Rnd_556x45_Stanag_plastic",4,30],["sfp_handgrenade_shgr56",2,1],["SmokeShellBlue",2,1]]],["sfp_backpack_sjvv9",[["Medikit",1],["ACE_adenosine",10],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_surgicalKit",1],["ACE_tourniquet",4],["ACE_splint",4],["ACE_salineIV_500",2],["ACE_plasmaIV_500",2],["ACE_bodyBag",1],["ACE_bloodIV_500",2],["ACE_quikclot",6],["ACE_packingBandage",4],["ACE_fieldDressing",4],["ACE_elasticBandage",2],["sfp_bandage",8]]],"sfp_m90w_helmet_nvg","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-KSP90",[["sfp_ksp90b","","","optic_Hamr",["sfp_200Rnd_556x45_ksp90",200],[],""],[],["sfp_p88","","","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_modern",[["ACE_EarPlugs",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_bloodIV_500",1],["ACE_bloodIV_250",1],["ACE_microDAGR",1],["ACE_morphine",4],["ACE_personalAidKit",1],["ACE_tourniquet",2],["ACE_Fortify",1],["O_NVGoggles_grn_F",1],["ACE_epinephrine",2],["ACE_splint",1],["ACE_plasmaIV_250",1]]],["sfp_kroppsskydd12_holster",[["muzzle_snds_L",1],["sfp_200Rnd_556x45_ksp90",2,200],["sfp_17Rnd_9x19_Mag",1,17],["SmokeShell",1,1],["Chemlight_green",2,1]]],["sfp_backpack_stridssack2000_ksp90",[["ACE_personalAidKit",1],["ACE_plasmaIV_250",1],["ACE_salineIV_250",1],["ACE_bloodIV_250",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MRE_LambCurry",1],["ACE_WaterBottle",1],["sfp_200Rnd_556x45_ksp90",5,200]]],"sfp_m90w_helmet_peltor","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-AT-GRG86",[["sfp_ak5c","","acc_pointer_IR","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_plastic",30],[],""],["sfp_grg86","","","",["sfp_grg_heat_mag",1],[],""],[],["sfp_m90w_uniform_modern",[["ACE_EarPlugs",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_bloodIV_250",1],["ACE_microDAGR",1],["ACE_morphine",4],["ACE_personalAidKit",1],["ACE_tourniquet",2],["ACE_Fortify",1],["O_NVGoggles_grn_F",1],["ACE_plasmaIV_250",1],["ACE_splint",1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",1,30]]],["sfp_kroppsskydd12_at",[["sfp_handgrenade_shgr56",2,1],["sfp_handgrenade_shgr2000",2,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",7,30],["SmokeShell",2,1],["Chemlight_green",2,1]]],["sfp_backpack_stridssack2000",[["muzzle_snds_M",1],["sfp_grg_heat_mag",3,1],["sfp_grg_he_mag",1,1],["SmokeShellGreen",1,1],["SmokeShell",2,1],["SmokeShellRed",1,1],["ACE_Chemlight_IR",1,1]]],"sfp_m90w_helmet_peltor","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-MachineGunner KSP58",[["sfp_ksp58B2","","","sfp_optic_3x_aimpoint",["sfp_50Rnd_762x51_ksp58",49],[],""],[],[],["sfp_m90w_uniform_modern",[["ACE_EarPlugs",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_bloodIV_500",1],["ACE_bloodIV_250",1],["ACE_microDAGR",1],["ACE_morphine",4],["ACE_personalAidKit",1],["ACE_tourniquet",2],["ACE_Fortify",1],["O_NVGoggles_grn_F",1],["ACE_epinephrine",2],["ACE_splint",1],["ACE_plasmaIV_250",1]]],["sfp_kroppsskydd12_mg",[["sfp_50Rnd_762x51_ksp58",2,49],["sfp_100Rnd_762x51_ksp58",1,100],["sfp_handgrenade_shgr56",2,1],["sfp_50Rnd_762x51_ksp58_irTracer",1,49]]],["sfp_backpack_stridssack08_ksp58",[["muzzle_snds_H_MG_blk_F",1],["sfp_100Rnd_762x51_ksp58",2,100],["sfp_50Rnd_762x51_ksp58_irTracer",2,49],["sfp_249Rnd_762x51_ksp58",1,249],["SmokeShell",2,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],"sfp_m90w_helmet_peltor","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-Rifelman AT Pskott Ammo carry KSP58",[["sfp_ak5c","","acc_pointer_IR","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_plastic",30],[],""],["sfp_pskott86","","","",[],[],""],[],["sfp_m90w_uniform_modern",[["ACE_EarPlugs",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_bloodIV_250",1],["ACE_microDAGR",1],["ACE_morphine",4],["ACE_personalAidKit",1],["ACE_tourniquet",2],["ACE_Fortify",1],["O_NVGoggles_grn_F",1],["ACE_plasmaIV_250",1],["ACE_splint",1],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",1,30]]],["sfp_kroppsskydd12_at",[["muzzle_snds_M",1],["bipod_01_F_blk",1],["SmokeShell",2,1],["sfp_handgrenade_shgr56",2,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",6,30],["Chemlight_green",2,1]]],["sfp_backpack_stridssack2000",[["B_IR_Grenade",1,1],["SmokeShellGreen",2,1],["sfp_handgrenade_shgr56",2,1],["sfp_handgrenade_shgr07",2,1],["sfp_50Rnd_762x51_ksp58_irTracer",4,49],["sfp_50Rnd_762x51_ksp58",4,49],["sfp_30Rnd_556x45_Stanag_tracer_plastic",8,30]]],"sfp_m90w_helmet_nvg","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],
 
   ["ACE-SFP-Expl Exp",[["sfp_remington870","","","",["sfp_12Gauge_8rd_Pellets",8],[],""],[],[],["sfp_m90w_uniform_modern",[["ACE_EarPlugs",1],["ACE_fieldDressing",3],["ACE_packingBandage",3],["ACE_quikclot",3],["ACE_bloodIV_250",2],["ACE_microDAGR",1],["ACE_morphine",4],["ACE_personalAidKit",1],["ACE_tourniquet",2],["ACE_Fortify",1],["O_NVGoggles_grn_F",1],["ACE_plasmaIV_250",1],["ACE_splint",1],["ACE_salineIV_250",1]]],["sfp_kroppsskydd12",[["sfp_handgrenade_shgr07",2,1],["SmokeShell",3,1],["SmokeShellGreen",2,1],["sfp_FlashBang",4,1],["Chemlight_green",2,1],["sfp_12Gauge_8rd_Pellets",4,8],["sfp_12Gauge_8rd_Slug",1,8]]],["sfp_backpack_stridssack2000",[["ACE_M26_Clacker",1],["ACE_DefusalKit",1],["MineDetector",1],["ToolKit",1],["sfp_sprdeg46_mag",8,1],["sfp_frdnmina13_mag",1,1],["DemoCharge_Remote_Mag",4,1]]],"sfp_m90w_helmet_nvg","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-Engineer",[["sfp_ak5c","","acc_pointer_IR","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_plastic",30],[],""],[],[],["sfp_m90w_uniform_modern",[["ACE_EarPlugs",1],["ACE_fieldDressing",3],["ACE_packingBandage",3],["ACE_quikclot",3],["ACE_bloodIV_250",2],["ACE_microDAGR",1],["ACE_morphine",4],["ACE_personalAidKit",1],["ACE_tourniquet",2],["ACE_Fortify",1],["O_NVGoggles_grn_F",1],["ACE_plasmaIV_250",1],["ACE_splint",1],["ACE_salineIV_250",1]]],["sfp_kroppsskydd12",[["muzzle_snds_M",1],["SmokeShell",3,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",8,30],["sfp_handgrenade_shgr07",2,1]]],["B_Carryall_green_F",[["ToolKit",1],["ACE_Clacker",1],["MineDetector",1],["ACE_wirecutter",1],["ACE_DefusalKit",1],["sfp_sprdeg46_mag",4,1],["sfp_strvm6_mag",1,1],["DemoCharge_Remote_Mag",2,1]]],"sfp_m90w_helmet_nvg","G_Combat_Goggles_tna_F",["ACE_MX2A","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-Helipilot",[["sfp_ak5d","","","",["sfp_30Rnd_556x45_Stanag_plastic",30],[],""],[],["sfp_p88","","","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m87_flying_suit",[["ACE_personalAidKit",1],["ACE_plasmaIV_250",1],["ACE_morphine",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_Fortify",1],["ACE_tourniquet",1],["ACE_splint",1],["ACE_salineIV_250",1],["ACE_quikclot",1],["ACE_packingBandage",1],["ACE_fieldDressing",1],["ACE_elasticBandage",1],["sfp_17Rnd_9x19_Mag",1,17],["SmokeShell",2,1],["sfp_handgrenade_shgr56",2,1]]],["sfp_kroppsskydd12_crew",[["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_WaterBottle",1],["ACE_EarPlugs",1],["muzzle_snds_M",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_tracer_plastic",4,30],["B_IR_Grenade",1,1],["sfp_handgrenade_shgr2000",2,1],["SmokeShellGreen",1,1],["SmokeShellRed",1,1],["SmokeShell",1,1],["Chemlight_green",1,1],["Chemlight_blue",1,1],["ACE_Chemlight_HiRed",1,1],["ACE_Chemlight_IR",1,1]]],[],"H_PilotHelmetHeli_B","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGogglesB_grn_F"]]],

    ["ACE-SFP-SOG-UAV",[["sfp_ak5c","muzzle_snds_M","sfp_dbal2","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_tracer_plastic",30],[],"bipod_01_F_blk"],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["NVGoggles",1],["ACE_personalAidKit",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",1,30]]],["V_PlateCarrier1_wdl",[["muzzle_snds_M",1],["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",2],["ACE_packingBandage",1],["ACE_elasticBandage",1],["ACE_fieldDressing",2],["SmokeShell",2,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",8,30],["sfp_handgrenade_shgr2000",3,1],["Chemlight_green",1,1],["Chemlight_blue",1,1]]],["B_UAV_01_backpack_F",[]],"sfp_m90w_booniehat","",["Binocular","","","",[],[],""],["ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG-KSP90",[["sfp_ksp90c","","acc_pointer_IR","sfp_optic_aimpoint",["sfp_200Rnd_556x45_ksp90",200],[],""],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["sfp_17Rnd_9x19_Mag",1,17]]],["V_PlateCarrier1_wdl",[["muzzle_snds_M",1],["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",2],["ACE_packingBandage",1],["ACE_elasticBandage",1],["ACE_fieldDressing",2],["SmokeShell",2,1],["sfp_200Rnd_556x45_ksp90",1,200],["sfp_handgrenade_shgr2000",3,1],["Chemlight_green",1,1],["Chemlight_blue",1,1],["sfp_17Rnd_9x19_Mag",2,17],["B_IR_Grenade",1,1]]],["sfp_backpack_stridssack2000",[["ACE_personalAidKit",3],["sfp_200Rnd_556x45_ksp90",3,200],["sfp_200Rnd_556x45_ksp90_irtracer",2,200],["sfp_sprdeg46_mag",4,1]]],"sfp_m90w_booniehat","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG(AT)",[["sfp_ak5c","muzzle_snds_M","sfp_dbal2","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_tracer_plastic",30],[],"bipod_01_F_blk"],["sfp_rb57","","","",[],[],""],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",1,30]]],["V_PlateCarrier1_wdl",[["muzzle_snds_M",1],["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",2],["ACE_packingBandage",1],["ACE_elasticBandage",1],["ACE_fieldDressing",2],["SmokeShell",2,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",8,30],["sfp_handgrenade_shgr2000",3,1],["Chemlight_green",1,1],["Chemlight_blue",1,1]]],[],"sfp_m90w_booniehat","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG-Demolitions",[["sfp_ak5c","muzzle_snds_M","sfp_dbal2","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_tracer_plastic",30],[],"bipod_01_F_blk"],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",1,30]]],["V_PlateCarrier1_wdl",[["muzzle_snds_M",1],["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",2],["ACE_packingBandage",1],["ACE_elasticBandage",1],["ACE_fieldDressing",2],["SmokeShell",2,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",8,30],["sfp_handgrenade_shgr2000",3,1],["Chemlight_green",1,1],["Chemlight_blue",1,1]]],["B_FieldPack_green_F",[["ACE_DefusalKit",1],["ACE_M26_Clacker",1],["MineDetector",1],["sfp_strvm5_mag",2,1],["sfp_sprdeg46_mag",4,1]]],"sfp_m90w_booniehat","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG-JTac",[["sfp_ak5c","muzzle_snds_M","sfp_dbal2","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_tracer_plastic",30],[],"bipod_01_F_blk"],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",1,30]]],["V_PlateCarrier1_wdl",[["muzzle_snds_M",1],["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",2],["ACE_packingBandage",1],["ACE_elasticBandage",1],["ACE_fieldDressing",2],["SmokeShell",2,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",8,30],["sfp_handgrenade_shgr2000",3,1],["Chemlight_green",1,1],["Chemlight_blue",1,1]]],[],"sfp_m90w_booniehat","",["Laserdesignator_03","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG-Medic",[["sfp_ak5c","muzzle_snds_M","sfp_dbal2","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_tracer_plastic",30],[],"bipod_01_F_blk"],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",1,30]]],["V_PlateCarrier1_wdl",[["muzzle_snds_M",1],["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",2],["ACE_packingBandage",1],["ACE_elasticBandage",1],["ACE_fieldDressing",2],["SmokeShell",4,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",8,30],["Chemlight_green",1,1],["Chemlight_blue",2,1],["SmokeShellBlue",2,1]]],["B_FieldPack_green_F",[["Medikit",1],["ACE_adenosine",10],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_surgicalKit",1],["ACE_tourniquet",4],["ACE_splint",4],["ACE_salineIV_500",2],["ACE_plasmaIV_500",2],["ACE_bodyBag",1],["ACE_bloodIV_500",2],["ACE_quikclot",10],["ACE_packingBandage",6],["ACE_fieldDressing",8],["ACE_elasticBandage",4],["sfp_bandage",8],["ACE_bloodIV_250",1],["ACE_plasmaIV_250",1],["ACE_salineIV_250",1],["ACE_IR_Strobe_Item",1]]],"sfp_m90w_booniehat","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG-Operator-SD",[["sfp_ak5c","muzzle_snds_M","sfp_dbal2","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_tracer_plastic",30],[],"bipod_01_F_blk"],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",1,30]]],["V_PlateCarrier1_wdl",[["muzzle_snds_M",1],["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",2],["ACE_packingBandage",1],["ACE_elasticBandage",1],["ACE_fieldDressing",2],["SmokeShell",2,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",8,30],["sfp_handgrenade_shgr2000",3,1],["Chemlight_green",1,1],["Chemlight_blue",1,1]]],[],"sfp_m90w_booniehat","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG-KSP58",[["sfp_ksp58B2","muzzle_snds_H_MG_blk_F","","sfp_optic_3x_aimpoint",["sfp_50Rnd_762x51_ksp58",49],[],""],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_fieldDressing",3],["ACE_packingBandage",4],["ACE_quikclot",4],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["ACE_bloodIV_250",1],["sfp_17Rnd_9x19_Mag",1,17]]],["V_PlateCarrier1_wdl",[["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",2],["ACE_packingBandage",1],["ACE_elasticBandage",1],["ACE_fieldDressing",2],["sfp_50Rnd_762x51_ksp58",2,49],["sfp_100Rnd_762x51_ksp58",2,100],["sfp_handgrenade_shgr2000",1,1],["sfp_17Rnd_9x19_Mag",2,17]]],["sfp_backpack_stridssack08_ksp58",[["ACE_personalAidKit",1],["sfp_100Rnd_762x51_ksp58",4,100],["sfp_249Rnd_762x51_ksp58",1,249],["SmokeShell",2,1]]],"sfp_m90w_booniehat","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG-GRG",[["sfp_ak5c","muzzle_snds_M","sfp_dbal2","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_tracer_plastic",30],[],"bipod_01_F_blk"],["sfp_grg86","","","",["sfp_grg_heat_mag",1],[],""],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",1,30]]],["V_PlateCarrier1_wdl",[["muzzle_snds_M",1],["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",2],["ACE_packingBandage",1],["ACE_elasticBandage",1],["ACE_fieldDressing",2],["SmokeShell",2,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",7,30],["sfp_handgrenade_shgr2000",3,1],["Chemlight_green",1,1],["Chemlight_blue",1,1],["sfp_17Rnd_9x19_Mag",1,17]]],["B_Carryall_green_F",[["sfp_17Rnd_9x19_Mag",1,17],["sfp_grg_heat_mag",2,1],["MRAWS_HE_F",1,1]]],"sfp_m90w_booniehat","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG-AG90",[["sfp_ag90_base","","","sfp_optic_kikarsikte90b_10x",["sfp_10Rnd_127x99_ag90",10],[],""],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["sfp_17Rnd_9x19_Mag",3,17]]],["V_PlateCarrier1_wdl",[["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",2],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",2],["ACE_packingBandage",1],["ACE_elasticBandage",1],["ACE_fieldDressing",2],["SmokeShell",2,1],["Chemlight_green",1,1],["Chemlight_blue",1,1],["sfp_10Rnd_127x99_ag90",3,10],["sfp_17Rnd_9x19_Mag",1,17]]],["B_FieldPack_green_F",[["ACE_Kestrel4500",1],["ACE_RangeCard",1],["sfp_17Rnd_9x19_Mag",2,17],["sfp_10Rnd_127x99_ag90",3,10],["ClaymoreDirectionalMine_Remote_Mag",1,1],["APERSBoundingMine_Range_Mag",1,1],["SmokeShell",2,1],["SmokeShellGreen",1,1],["sfp_handgrenade_shgr07",3,1]]],"sfp_m90w_booniehat","",["ACE_Yardage450","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG-TL",[["sfp_ak5c_m203","","","sfp_optic_aimpoint",["sfp_30Rnd_556x45_Stanag_plastic",30],["1Rnd_HE_Grenade_shell",1],""],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_m90w_uniform_dirty",[["O_NVGoggles_grn_F",1],["ACE_personalAidKit",1],["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",1,30]]],["V_PlateCarrier2_wdl",[["muzzle_snds_M",1],["ACE_microDAGR",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",1],["ACE_plasmaIV_250",1],["ACE_morphine",2],["ACE_personalAidKit",1],["ACE_epinephrine",2],["ACE_bloodIV_250",1],["ACE_quikclot",1],["ACE_packingBandage",1],["ACE_fieldDressing",2],["ACE_Flashlight_XL50",1],["SmokeShell",2,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",6,30],["sfp_handgrenade_shgr2000",3,1],["Chemlight_green",1,1],["Chemlight_blue",1,1],["rhs_mag_M441_HE",3,1]]],["B_FieldPack_green_F",[["ACE_HuntIR_monitor",1],["ACE_IR_Strobe_Item",1],["ACE_Kestrel4500",1],["ACE_personalAidKit",1],["ACE_morphine",1],["ACE_epinephrine",1],["ACE_bloodIV_250",1],["ACE_quikclot",1],["1Rnd_HE_Grenade_shell",26,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",2,30],["ACE_HuntIR_M203",2,1],["rhs_mag_M585_white",1,1],["ACE_40mm_Flare_green",1,1],["ACE_40mm_Flare_red",1,1],["ACE_40mm_Flare_ir",1,1],["1Rnd_Smoke_Grenade_shell",4,1]]],"sfp_m90w_booniehat","",["Laserdesignator_03","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

    ["ACE-SFP-SOG-spotter",[["sfp_ak5b","muzzle_snds_M","","optic_Hamr",["sfp_30Rnd_556x45_Stanag_plastic",30],[],""],[],["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],["sfp_ghillie_uniform",[["ACE_personalAidKit",1],["O_NVGoggles_grn_F",1],["ACE_EarPlugs",1],["ACE_quikclot",2],["ACE_packingBandage",2],["ACE_elasticBandage",2],["ACE_fieldDressing",2],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_tourniquet",2],["ACE_splint",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_30Rnd_556x45_Stanag_irtracer_plastic",1,30]]],["V_PlateCarrier1_wdl",[["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["ACE_personalAidKit",1],["ACE_plasmaIV_250",1],["ACE_bloodIV_250",1],["ACE_CableTie",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["ACE_microDAGR",1],["ACE_SpottingScope",1],["SmokeShell",2,1],["sfp_handgrenade_shgr2000",2,1],["sfp_30Rnd_556x45_Stanag_tracer_plastic",5,30]]],[],"sfp_m90w_booniehat","",["Rangefinder","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],

["ACE-SFP-SOG-Sniper",
	[
		["sfp_psg90_base","muzzle_snds_B_lush_F","","sfp_optic_kikarsikte90b_10x",["sfp_9Rnd_762x51_psg90",9],[],""],
		[],
		["sfp_p88","muzzle_snds_L","sfp_tlr2","",["sfp_17Rnd_9x19_Mag",17],[],""],
		["sfp_ghillie_uniform",[["ACE_personalAidKit",1],["O_NVGoggles_grn_F",1],["ACE_EarPlugs",1],["ACE_quikclot",2],["ACE_packingBandage",2],["ACE_elasticBandage",2],["ACE_fieldDressing",2],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_tourniquet",2],["ACE_splint",1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_9Rnd_762x51_psg90_prick",1,9]]],
		["V_PlateCarrier1_wdl",[["ACE_fieldDressing",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",3],["ACE_tourniquet",2],["ACE_splint",1],["ACE_Fortify",1],["ACE_personalAidKit",1],["ACE_plasmaIV_250",1],["ACE_bloodIV_250",1],["ACE_CableTie",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["ACE_microDAGR",1],["ACE_SpottingScope",1],["ACE_RangeCard",1],["SmokeShell",2,1],["sfp_handgrenade_shgr2000",2,1],["sfp_17Rnd_9x19_Mag",1,17],["sfp_9Rnd_762x51_psg90",4,9]]],
		[],
		"sfp_m90w_booniehat","",["Rangefinder","","","",[],[],""],
		["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]
	]
],
